### ISSUE TITLE
Some improvement suggestions for pine64-diagnostics.sh

### ISSUE THREAD

**Issue by ThomasKaiser** [pfeerick/pine64-scripts#3]
For the very simple reason to make ayufan's OMV images as compatible as possible to Armbian's I would propose the following changes:

- implement also the monitoring mode (`-m` switch)
- make it compatible to ROCK64 and future boards that are handled by Pine community
- replace therefore in `DisplayUsage` function all occurences of the hard coded script name with `${0##*/}`

This allows @ayufan to create a symlink called `armbianmonitor` to this script and at least `-u` and `-m` (the two functions I train OMV forum moderators currently with ;) ) functionality works. So for curious OMV users it really doesn't matter whether they fetch OMV version from Pine wiki or soon Pine Installer or later when an Armbian based OMV version is available from official OMV download page.

That's my main concern: Avoiding confusion.

**Comment by ayufan** [comment]
Oh. These are great ideas! Thanks @ThomasKaiser for writing that :)

**Comment by pfeerick** [comment]
@ThomasKaiser All great ideas, and thanks for the PR! ;) 

Have made a few minor amendments as you can see from the commit history. Only niggling issue is that to access the CPU frequency parameter root access is required, so it breaks the script cosmetically with an access error. Is your preference that it simply require root access (current change), or instead do a permissions test and say something like ROOTREQ where the CPU freq is listed to absorb the error. As it stands, this is a standalone script, so I wasn't intending on pulling in the daemon to allow rootless access to the cpufreq ;)

**Comment by ayufan** [comment]
Can we fix frequency to be accessuble?

**Comment by ThomasKaiser** [comment]
@pfeerick I see another problem with unprivileged mode: `/var/log/` should not be writable by normal users?

    root@lime2:~# ls -lad /var/log
    drwxrwxr-x 1 root syslog 3688 Jul 22 06:35 /var/log

That's default Ubuntu permissions, I doubt it will be different in Debian. So how to deal with that?

Wrt CPU frequency there's a difference between

    /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq (we currently use)

and

    /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq (accessible by everyone)

Some background info: https://unix.stackexchange.com/questions/87522/why-do-cpuinfo-cur-freq-and-proc-cpuinfo-report-different-numbers

So let's either switch to `scaling_cur_freq` or let's skip cpufreq display when user can't access the file (also easy). I don't remember exactly when/why I switched to `cpuinfo_cur_freq` but most probably it was with a smelly Allwinner kernel where `cpuinfo_cur_freq` showed correct values while `scaling_cur_freq` not.

**Comment by pfeerick** [comment]
@ayufan Through the script, no. If there is some neat way you can change the permissions of `/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_cur_freq` from the 400 it is currently to 444, that would would fix it ;) (and do it to all the /sys/devices/system/cpu/cpu[0,3] to be consistent I suppose). 

Ok, and since @ThomasKaiser replied whilst I was writing that... lets make it so that it tries `cpuinfo_cur_freq` first, and then falls back to `scaling_cur_freq` if the permissions don't fit. And hopefully that doesn't give us useless results, else it's revert back to a no-show so it doesn't need root for monitor mode.

And regarding the `/var/log` permissions... that isn't an issue as yet... the only part of the script that uses the log file is the upload mode, and that needs root privileges, for dependency installation and something else to do with the log generation. Otherwise I suppose writing to the current / user home folder and a message saying that is where it is would probably be the alternative.

**Comment by pfeerick** [comment]
I'm calling this closed for now as of https://github.com/pfeerick/pine64-scripts/commit/e9b75e6d5393321f395d41c5b88d4d8a9b214d44. If there's related or further issues, please re-open or create another issue as you see fit.

**Comment by ayufan** [comment]
@pfeerick according to Google in all cases we should read `scaling_cur_freq` :)

**Comment by pfeerick** [comment]
True. But are the usual discussions talking about Allwinner ARM stuff, or desktop systems? And then there is also the issue which Thomas mentioned above, with Allwinner kernels giving the incorrect values in scaling_cur_freq, and correct values cpuinfo_cur_freq. I'll do some tests on the rock64 and pine64/pinebook kernels, and if they don't screw up, I'm happy to change it, but then there is the need for the 444 permission change. 

It is suggested that  "for some processors, cpuinfo_cur_freq involves a hardware read and can be "expensive" in terms of time, which is the reason it requires sudo to access." ... so the the sudo/root priv certainly doesn't appear to be accidental.

Going by the [kernel cpu-freq documentation](https://www.kernel.org/doc/Documentation/cpu-freq/user-guide.txt), I'm still wondering if this is an academic argument of sorts... "actual" vs "kernel"... hm.... 

> cpuinfo_cur_freq :		Current frequency of the CPU as obtained from
				the hardware, in KHz. This is the frequency
				the CPU actually runs at.

> scaling_cur_freq :		Current frequency of the CPU as determined by
				the governor and cpufreq core, in KHz. This is
				the frequency the kernel thinks the CPU runs
				at.

**Comment by ThomasKaiser** [comment]
> And then there is also the issue which Thomas mentioned above, with Allwinner kernels giving the incorrect values in scaling_cur_freq, and correct values cpuinfo_cur_freq.

As already said I don't remember why/when I switched to this. I think a quick throttling test with Pine64 and ROCK64 should be sufficient. Read both values in a loop and let cpuburn-a53 run. If readouts differ we have to investigate further if not let's only use `scaling_cur_freq` which has the appropriate permissions and move on to something more interesting :)

@ayufan please ping me if you're done including Pete's script with the appropriate symlink to `/usr/local/bin/armbianmonitor`. For whatever reasons I'm soon moderator in OMV forum and want to 'feature' ROCK64 as OMV device there focusing on

- hardware capabilities
- open source development (partially happened at Armbian, partially at OMV, now in Pine community)
- explain why OS images created from scratch are the only reasonable option (to also put more pressure on other image creators to improve)

In the end I want this to be an open source success story focusing on how fast we can get from nowhere to optimal if everything happens in the open.

**Comment by ayufan** [comment]
Wow. I like your approach. I will be happy to help with this :)

**Comment by pfeerick** [comment]
Nice thinking ;)

Right, there is a quick test script here to compare the two : https://github.com/pfeerick/pine64-scripts/blob/master/testing/quickcputest.sh

I ran it on the pine64 and rock64. Both units had heatsinks, so I let it run for 2x15 rows (header row is the mark for 15) and then 'assisted' the throttling process with some heat for either 2 or 3 groups, and then left it to recover. You can see the [rock64 results here](https://pastebin.com/SYv5ZNeC), and the [pine64 results here](https://pastebin.com/zBv0hueC). 

To my mind, the pine64 showed only one single discrepancy between the two, meaning for it, I think either is fine. The rock64 showed more variance, but the two values still tracked each other... one was leading the other following, and vice versa. I think they are both valid, it's just that cpuinfo (when implemented properly) is the current value, whereas scaling is a buffered value, and the polling frequency a bit slower?  Your thoughts? And once we've gotten this nailed, I'm happy to do another PR to both the rock64 and pine64 linux-build repos to get this included for some more real world testing ;) 

It's in my rock64-linux-build fork here: https://github.com/pfeerick-rock64/linux-build/commit/f080dc435f52bffd4b370ee628a34bea630ade12

And in my pine64-linux-build fork here: https://github.com/pfeerick-pine64/linux-build/commit/1bc36e1bd66af7c23b26195b5d3f73c4d3d032e4

Just need to make any final changes based on feedback and then I'll do the PR requests...

**Comment by ThomasKaiser** [comment]
@pfeerick thanks for testing. Based on results I think it's fine to choose `scaling_cur_freq` as only source for now. It's precise enough for what should people do with it (get an *idea* about throttling effects) and then there's always RPi-Monitor (which reminds me that I still need to explore available voltage readouts below sysfs for ROCK64).
