### ISSUE TITLE
Update to install-arduino-ide.sh

### ISSUE THREAD

**Issue by jrullan** [pfeerick/pine64-scripts#8]
First of all thank you very much for your hard work.

I updated a copy of this script in my pine and noticed that in order to use arduino ide version 1.8.5 the fix for the serial monitor needed some changes: I had to modify the script to point to the file jssc-2.8.0-arduino1.jar.

Apparently this filename was changed at some point between 1.8.3 and 1.8.5...

**Comment by pfeerick** [comment]
lol... that would be right ;) Thanks for picking up and reporting that... I'll be getting back to doing stuff on pine64/pinebook within the next few weeks so I'll make the changes when I roll up to 1.8.5
